/**
 * \file HsslSingleDemo.c
 * \brief Demo HsslSingleDemo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "HsslSingleDemo.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

App_HsslSingle g_HsslSingle; /**< \brief Demo information */

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \addtogroup IfxLld_Demo_HsslSingle_SrcDoc_Main_Interrupt
 * \{ */

/** \} */

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void HsslSingleDemo_init(void)
{
    /* create Hsct module config */
    IfxHssl_Hssl_initHsctModuleConfig(&g_HsslSingle.drivers.hsctConfig, &MODULE_HSCT0);

    /* choose master or slave */
    g_HsslSingle.drivers.hsctConfig.interfaceMode = IfxHssl_InterfaceMode_master;
    g_HsslSingle.drivers.hsctConfig.highSpeedMode = TRUE; /* interface at high speed */

    /* create Hssl module config */
    IfxHssl_Hssl_initHsslModuleConfig(&g_HsslSingle.drivers.hsslConfig, &MODULE_HSSL0);
	
	/* initialize Hsct module */
    IfxHssl_Hssl_initHsctModule(&g_HsslSingle.drivers.hsct, &g_HsslSingle.drivers.hsctConfig);
	
	/* initialize Hssl module */
    IfxHssl_Hssl_initHsslModule(&g_HsslSingle.drivers.hssl, &g_HsslSingle.drivers.hsslConfig);

    /* create HSSL channel config */
    IfxHssl_Hssl_ChannelConfig hsslChannelConfig;
    IfxHssl_Hssl_initChannelConfig(&hsslChannelConfig, &g_HsslSingle.drivers.hssl, &g_HsslSingle.drivers.hsct);

    uint32                     i;

    for (i = 0; i < 4; ++i)
    {
        hsslChannelConfig.channelId = (IfxHssl_ChannelId)i;
        IfxHssl_Hssl_initChannel(&g_HsslSingle.drivers.hsslChannel[i], &hsslChannelConfig);
    }

    printf("Hssl is initialised\n");
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void HsslSingleDemo_run(void)
{
    if (g_HsslSingle.drivers.hsctConfig.interfaceMode == IfxHssl_InterfaceMode_slave)
    {
        while (1)
        {}
    }

    else if (g_HsslSingle.drivers.hsctConfig.interfaceMode == IfxHssl_InterfaceMode_master)
    {
        /* write some data to remote location: */
        IfxHssl_Hssl_write(&g_HsslSingle.drivers.hsslChannel[0], 0x70000000, 0x12345678, IfxHssl_DataLength_32bit);

        while (IfxHssl_Hssl_waitAcknowledge(&g_HsslSingle.drivers.hsslChannel[0]) != IfxHssl_Hssl_Status_ok)
        {
            if (IfxHssl_Hssl_waitAcknowledge(&g_HsslSingle.drivers.hsslChannel[0]) == IfxHssl_Hssl_Status_error)
            {
                IfxHssl_Hssl_checkErrors(&g_HsslSingle.drivers.hssl);
                break;
            }
        }

        IfxHssl_Hssl_write(&g_HsslSingle.drivers.hsslChannel[0], 0x70000004, 0xaabbccdd, IfxHssl_DataLength_32bit);

        while (IfxHssl_Hssl_waitAcknowledge(&g_HsslSingle.drivers.hsslChannel[0]) == IfxHssl_Hssl_Status_busy)
        {}

        /* read some data from remote location: */
        IfxHssl_Hssl_read(&g_HsslSingle.drivers.hsslChannel[0], 0x70000000, IfxHssl_DataLength_32bit);

        while (IfxHssl_Hssl_waitAcknowledge(&g_HsslSingle.drivers.hsslChannel[0]) != IfxHssl_Hssl_Status_ok)
        {
            if (IfxHssl_Hssl_waitAcknowledge(&g_HsslSingle.drivers.hsslChannel[0]) == IfxHssl_Hssl_Status_error)
            {
                IfxHssl_Hssl_checkErrors(&g_HsslSingle.drivers.hssl);
                break;
            }
        }

        uint32 dataL = IfxHssl_Hssl_getReadData(&g_HsslSingle.drivers.hsslChannel[0]);

        IfxHssl_Hssl_read(&g_HsslSingle.drivers.hsslChannel[0], 0x70000004, IfxHssl_DataLength_32bit);

        while (IfxHssl_Hssl_waitAcknowledge(&g_HsslSingle.drivers.hsslChannel[0]) == IfxHssl_Hssl_Status_busy)
        {}

        uint32 dataU = IfxHssl_Hssl_getReadData(&g_HsslSingle.drivers.hsslChannel[0]);

        /* Check received data */
        uint32 errors = 0;

        if (dataL != 0x12345678)
        {
            ++errors;
        }

        if (dataU != 0xaabbccdd)
        {
            ++errors;
        }

        {
            unsigned int *target = (unsigned int *)0x70000010;
            target[0] = dataL;
            target[1] = dataU;
        }

        if (errors)
        {
            printf("ERROR: Found (%lu errors)\n", errors);
        }
        else
        {
            printf("OK: Checks passed\n");
        }
    }

    printf("Hssl Single data transactions are finished\n");
}
