/**
 * \file ScuEruDemo.c
 * \brief Demo ScuEruDemo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "ScuEruDemo.h"
#include "Src/Std/IfxSrc.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

App_ScuEru g_ScuEru; /**< \brief Demo information */

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \addtogroup IfxLld_Demo_ScuEru_SrcDoc_Main_Interrupt
 * \{ */

/** \name Interrupts for input state change
 * \{ */

IFX_INTERRUPT(ISR_ScuEru, 0, ISR_PRIORITY_SCUERU_0);

/** \} */

/** \} */

/** \brief Handle Timer interrupt.
 *
 * \isrProvider \ref ISR_PROVIDER_SCUERU_0
 * \isrPriority \ref ISR_PRIORITY_SCUERU_0
 *
 */
void ISR_ScuEru(void)
{
    IfxCpu_enableInterrupts();

    printf("ISR_ScuEru invoked\n");

    g_ScuEru.count++;
}


/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void ScuEruDemo_init(void)
{
    /* disable interrupts */
    boolean        interruptState = IfxCpu_disableInterrupts();

    /* select external request pin */
    IfxScu_Req_In *reqPin = &IfxScu_REQ6A_P20_0_IN;

    /* initialize this pin with pull-up enabled */
    /* this function will also configure the input multiplexers of the ERU (EICRm.EXISx) */
    IfxScuEru_initReqPin(reqPin, IfxPort_InputMode_pullUp);

    /* determine input channel EICRm depending on input pin */
    IfxScuEru_InputChannel inputChannel = (IfxScuEru_InputChannel)reqPin->channelId;

    /* signal destination */
    IfxScuEru_InputNodePointer triggerSelect = IfxScuEru_InputNodePointer_0;                           /* TRx0 */
    IfxScuEru_OutputChannel    outputChannel = IfxScuEru_OutputChannel_0;                              /* OGU channel 0 */

    /* input channel configuration */
    IfxScuEru_disableFallingEdgeDetection(inputChannel);                                               /* EICRm.FENn */
    IfxScuEru_enableRisingEdgeDetection(inputChannel);                                                 /* EICRm.RENn */
    IfxScuEru_enableAutoClear(inputChannel);                                                           /* EICRm.LDENn */

    /* Connecting Matrix, Event Trigger Logic ETL block */
    IfxScuEru_enableTriggerPulse(inputChannel);                                                        /* EICRm.EIENn */
    IfxScuEru_connectTrigger(inputChannel, triggerSelect);                                             /* EICRm.INPn */

    /* output channels, OutputGating Unit OGU block */
    IfxScuEru_setFlagPatternDetection(outputChannel, inputChannel, TRUE);                              /* IGCRm.IPENn */
    IfxScuEru_enablePatternDetectionTrigger(outputChannel);                                            /* IGCRm.GEENn */
    IfxScuEru_setInterruptGatingPattern(outputChannel, IfxScuEru_InterruptGatingPattern_alwaysActive); /* IGCEm.IGPn */

    /* service request configuration */
    {
        volatile Ifx_SRC_SRCR *src = &MODULE_SRC.SCU.SCUERU[(int)outputChannel % 4];
        IfxSrc_init(src, ISR_PROVIDER_SCUERU_0, ISR_PRIORITY_SCUERU_0);
        IfxSrc_enable(src);
    }

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);

    printf("Scu Eru is initialised and running\n");
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void ScuEruDemo_run(void)
{
    /* wait for 3 events */
    g_ScuEru.count = 0;

    while (g_ScuEru.count < 3)
    {}
}
