/**
 * \file I2cBasicDemo.c
 * \brief Demo I2cBasicDemo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "I2cBasicDemo.h"
#include <Cpu/Std/IfxCpu.h>
/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
App_I2cBasic g_I2cBasic; /**< \brief Demo information */

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void I2cBasicDemo_init(void)
{
    /* disable interrupts */
    boolean   interruptState = IfxCpu_disableInterrupts();

    //Ifx_SizeT size;
    g_I2cBasic.i2cAddr = 0xa0;

    {   /* init Module */
        IfxI2c_I2c_Config config;

        IfxI2c_I2c_initConfig(&config, &MODULE_I2C0);

        const IfxI2c_Pins pins = {&IfxI2c0_SCL_P02_5_INOUT, &IfxI2c0_SDA_P02_4_INOUT, IfxPort_PadDriver_ttlSpeed1};

        config.pins     = &pins;
        config.baudrate = 400000;       /* 400 kHz */

        IfxI2c_I2c_initModule(&g_I2cBasic.i2c, &config);
    }

    {                                                                   /* init slave devices */
        IfxI2c_I2c_deviceConfig i2cDeviceConfig;
        IfxI2c_I2c_initDeviceConfig(&i2cDeviceConfig, &g_I2cBasic.i2c); /* Device config for Bus of i2c handle */

        i2cDeviceConfig.deviceAddress = g_I2cBasic.i2cAddr;
        IfxI2c_I2c_initDevice(&g_I2cBasic.i2cDev, &i2cDeviceConfig);
    }

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void I2cBasicDemo_run(void)
{
    uint32    i;
    Ifx_SizeT size;
    printf("I2cBasicDemo_run() called\n");

    printf("Read\n");

    for (i = 0; i < DATA_SIZE; i++)
    {
        g_I2cBasic.data[i] = 0xee;
    }

    size = 10;      /* number of bytes to rx */

    while (IfxI2c_I2c_read(&g_I2cBasic.i2cDev, g_I2cBasic.data, size) == IfxI2c_I2c_Status_nak)
    {}

    for (i = 0; i < 10; i++)
    {
        if (g_I2cBasic.data[i] == i + 1)
        {
            printf("workingn\n");
        }
    }

    printf("Write\n");

    for (i = 0; i < 10; i++)
    {
        g_I2cBasic.data[i] = 0x10 + i;
    }

    size = 10;      /* number of bytes to tx */

    while (IfxI2c_I2c_write(&g_I2cBasic.i2cDev, g_I2cBasic.data, size) == IfxI2c_I2c_Status_nak)
    {}
}
