/**
 * \file Template.h
 * \brief Qspi Master & Slave Demo (using cpu)
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 *
 * \defgroup IfxLld_Demo_QspiCpuDemo_SrcDoc_Main Demo Source
 * \ingroup IfxLld_Demo_QspiCpuDemo_SrcDoc
 * \defgroup IfxLld_Demo_QspiCpuDemo_SrcDoc_Main_Interrupt Interrupts
 * \ingroup IfxLld_Demo_QspiCpuDemo_SrcDoc_Main
 */

#ifndef QSPICPUDEMO_H
#define QSPICPUDEMO_H 1

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/
#include <Ifx_Types.h>
#include "Configuration.h"
#include <Qspi/SpiMaster/IfxQspi_SpiMaster.h>
#include <Qspi/SpiSlave/IfxQspi_SpiSlave.h>

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
#define SPI_BUFFER_SIZE 10   /**< \brief Tx/Rx Buffer size */

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/
typedef struct
{
    uint8 spi0TxBuffer[SPI_BUFFER_SIZE];                   /**< \brief Qspi0 Transmit buffer */
    uint8 spi0RxBuffer[SPI_BUFFER_SIZE];                   /**< \brief Qspi0 receive buffer */
    uint8 spi2TxBuffer[SPI_BUFFER_SIZE];                   /**< \brief Qspi2 Transmit buffer */
    uint8 spi2RxBuffer[SPI_BUFFER_SIZE];                   /**< \brief Qspi2 receive buffer */
} AppQspiBuffer;

/** \brief QspiCpu global data */
typedef struct
{
    AppQspiBuffer qspiBuffer;                       /**< \brief Qspi buffer */
    struct
    {
        IfxQspi_SpiMaster         spiMaster;        /**< \brief Spi Master handle */
        IfxQspi_SpiMaster_Channel spiMasterChannel; /**< \brief Spi Master Channel handle */
        IfxQspi_SpiSlave          spiSlave;         /**< \brief Spi Slave handle */
    }drivers;
} App_QspiCpu;

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
IFX_EXTERN App_QspiCpu g_QspiCpu;

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/
IFX_EXTERN void IfxQspiCpuDemo_init(void);
IFX_EXTERN void IfxQspiCpuDemo_run(void);

#endif
