/**
 * \file Ccu6IcuDemo.c
 * \brief Demo Ccu6IcuDemo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "Ccu6IcuDemo.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

App_Ccu6Icu g_Ccu6Icu; /**< \brief Demo information */

/* pin configuration, in case of multi input capture mode select the respective CC6xIn and CCPOSxIn pins of the selected channel */
IfxCcu6_Icu_Pins pins = {
    &IfxCcu60_CC60INA_P02_0_IN, /* CC60In pin */
    NULL_PTR,                   /* CC61In pin not used */
    NULL_PTR,                   /* CC62In pin not used */
    NULL_PTR,                   /* CCPOS0In pin not used */
    NULL_PTR,                   /* CCPOS1In pin not used */
    NULL_PTR,                   /* CCPOS2In pin not used */
    IfxPort_InputMode_pullUp,
    IfxPort_InputMode_pullUp,
    NULL_PTR,
    NULL_PTR,
    IfxPort_InputMode_pullUp
};

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \addtogroup IfxLld_Demo_Ccu6Icu_SrcDoc_Main_Interrupt
 * \{ */

/** \name Interrupts for Capture
 * \{ */

IFX_INTERRUPT(ccu6_ISR_Icu, 0, ISR_PRIORITY_CCU6_ICU);

/** \} */

/** \} */

/** \brief Handle Capture interrupt.
 *
 * \isrProvider \ref ISR_PROVIDER_CCU6_ICU
 * \isrPriority \ref ISR_PRIORITY_CCU6_ICU
 *
 */
void ccu6_ISR_Icu(void)
{
    IfxCpu_enableInterrupts();

    IfxCcu6_clearInterruptStatusFlag(&MODULE_CCU60, IfxCcu6_InterruptSource_cc60RisingEdge);

    /* store the time stamp in an array */
    g_Ccu6Icu.timeStamp[g_Ccu6Icu.count] = IfxCcu6_Icu_getTimeStamp(&g_Ccu6Icu.drivers.icuChannel);
    g_Ccu6Icu.count++;
}


/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void Ccu6IcuDemo_init(void)
{
    /* disable interrupts */
    boolean            interruptState = IfxCpu_disableInterrupts();

    /* create configuration */
    IfxCcu6_Icu_Config icuConfig;
    IfxCcu6_Icu_initModuleConfig(&icuConfig, &MODULE_CCU60);

    /* configure the frequency of the timer in case of internal start */
    icuConfig.frequency = 400000;

    /* configure the period of the timer */
    icuConfig.period = 100;

    /* configure the clock for internal mode */
    icuConfig.clock.extClockEnabled = FALSE;

    /* configure count operation */
    icuConfig.countMode    = IfxCcu6_T12CountMode_edgeAligned;
    icuConfig.counterValue = 0;

    /* initialize the module */
    IfxCcu6_Icu_initModule(&g_Ccu6Icu.drivers.icu, &icuConfig);

    /* create Icu channel config */
    IfxCcu6_Icu_ChannelConfig icuChannelConfig;
    IfxCcu6_Icu_initChannelConfig(&icuChannelConfig, &MODULE_CCU60);

    /* configure the channel */
    icuChannelConfig.channelId   = IfxCcu6_T12Channel_0;
    icuChannelConfig.channelMode = IfxCcu6_T12ChannelMode_doubleRegisterCaptureRising;

    /* configure the interrupts */
    icuChannelConfig.interrupt1.source         = IfxCcu6_InterruptSource_cc60RisingEdge;
    icuChannelConfig.interrupt1.serviceRequest = IfxCcu6_ServiceRequest_2;
    icuChannelConfig.interrupt1.priority       = ISR_PRIORITY_CCU6_ICU;
    icuChannelConfig.interrupt1.typeOfService  = ISR_PROVIDER_CCU6_ICU;

    /* configure input and output triggers */
    icuChannelConfig.trigger.extInputTrigger = NULL_PTR;

    icuChannelConfig.pins = &pins;

    /* configure multi input capture mode */
    icuChannelConfig.multiInputCaptureEnabled = FALSE;

    /* initialize the channel */
    IfxCcu6_Icu_initChannel(&g_Ccu6Icu.drivers.icuChannel, &icuChannelConfig);

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);

    printf("Ccu6 Icu is initialised\n");

    IfxCcu6_Icu_startCapture(&g_Ccu6Icu.drivers.icuChannel);
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void Ccu6IcuDemo_run(void)
{}
