/**
 * \file EbuSramDemo.c
 * \brief Ebu Sram Demo.
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "Cpu0_Main.h"
#include <Ebu/Sram/IfxEbu_Sram.h>
#include "IfxPort.h"
#include "Ifx_Assert.h"
#include "EbuSramDemo.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
#define EBUSRAM_CS1_START_ADDRESS (0xa4000000)  /**< \brief ChipSelect 1 Start address */
#define EBUSRAM_CS0_START_ADDRESS (0xa8000000)  /**< \brief ChipSelect 0 Start address */

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void IfxEbuSramDemo_init(void)
{
    IfxEbu_Sram        sram;
    IfxEbu_Sram_Config cfg;

    /* enable byte control pins */
    IfxEbu_setByteControlEnable(&MODULE_EBU, IfxEbu_ByteControlEnable_byteControl32Bit);

    /* get default SRAM configuration */
    IfxEbu_Sram_initMemoryConfig(&cfg, &MODULE_EBU);

    /* Configure CS#0 */
    cfg.chipSelect                     = IfxEbu_ChipSelect_0;
    cfg.memoryRegionConfig.baseAddress = EBUSRAM_CS0_START_ADDRESS; /* specify noncached segment A, driver will also enable the cached segment 8 */
    IfxEbu_Sram_initMemory(&sram, &cfg);

    /* Configure CS#1 */
    cfg.chipSelect                     = IfxEbu_ChipSelect_1;
    cfg.memoryRegionConfig.baseAddress = EBUSRAM_CS1_START_ADDRESS; /* specify noncached segment A, driver will also enable the cached segment 8 */
    cfg.device                         = IfxEbu_Sram_Device_deMuxedAsynchronousType;
    /* configuring the device type for read */
    cfg.readConfig.deviceInterface     = IfxEbu_ExternalDeviceInterface_32bitMultiplexed;
    /* configuring the device type for write */
    cfg.writeConfig.deviceInterface    = IfxEbu_ExternalDeviceInterface_32bitMultiplexed;
    /* Configure the wait states */
    cfg.writeAccessParameter.waitState = 0x12;
    IfxEbu_Sram_initMemory(&sram, &cfg);
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void IfxEbuSramDemo_run(void)
{
    uint32           i;
    uint32           errors;
    volatile uint32 *sramAddress;

    sramAddress = (volatile uint32 *)(EBUSRAM_CS1_START_ADDRESS);
    errors      = 0;

    for (i = 0; i < 64; i++)
    {
        sramAddress[i] = 0xAABBCC00 + i;
    }

    for (i = 0; i < 64; i++)
    {
        uint32 sramData     = sramAddress[i];
        uint32 expectedData = 0xAABBCC00 + i;

        if (sramData != expectedData)
        {
            printf("Error @ sramAddress: 0x%08x = value: 0x%08x , Expected value: 0x%08x\n", (unsigned int) (sramAddress + i), (unsigned int)sramData,(unsigned int) expectedData);
            errors++;
        }
    }

    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, errors == 0);

    if (errors)
    {
        printf("ERROR: Sram written data doesn't match with read data (%d mismatches)\n", (int)errors);
    }
    else
    {
        printf("OK: Sram written data matches with read data\n");
    }
}
