/**
 * \file Psi5SDemo.c
 * \brief Psi5S Demo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "Psi5SDemo.h"
/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

App_Psi5S g_Psi5S; /**< brief Psi5S global data */
/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void IfxPsi5SDemo_init(void)
{
    printf("IfxPsi5SDemo_init() called\n");

    IfxPsi5s_Psi5s_Config        psi5sModuleConfig;
    IfxPsi5s_Psi5s_initModuleConfig(&psi5sModuleConfig, &MODULE_PSI5S);
    IfxPsi5s_Psi5s_initModule(&g_Psi5S.psi5s, &psi5sModuleConfig);

    IfxPsi5s_Psi5s_ChannelConfig psi5sChannelConfig;
    IfxPsi5s_Psi5s_initChannelConfig(&psi5sChannelConfig, &g_Psi5S.psi5s);

    psi5sChannelConfig.channelId = IfxPsi5s_ChannelId_4;
    int                          slot;

    for (slot = 0; slot < 6; ++slot)
    {
        psi5sChannelConfig.receiveControl.payloadLength[slot] = 8;
    }

    psi5sChannelConfig.channelId = IfxPsi5s_ChannelId_4;

    /* initialize the channel*/
    IfxPsi5s_Psi5s_initChannel(&g_Psi5S.psi5sChannel, &psi5sChannelConfig);
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void IfxPsi5SDemo_run(void)
{
    printf("IfxPsi5SDemo_run() called\n");

    uint32 channels = (1 << IfxPsi5s_ChannelId_4);                 /* enable channel 4*/
    uint32 mask     = (1 << IfxPsi5s_ChannelId_4);                 /* modify the selection for channel 4*/

    IfxPsi5s_Psi5s_enableDisableChannelTriggerCounters(&g_Psi5S.psi5s, channels, mask);

    /* enable the channel*/
    IfxPsi5s_Psi5s_enableDisableChannels(&g_Psi5S.psi5s, channels, mask);

    /* start ASC interface*/
    IfxPsi5s_Psi5s_startAscTransactions(&g_Psi5S.psi5s);

    uint32 data = 0x5;

    /* send data*/
    if (IfxPsi5s_Psi5s_sendChannelData(&g_Psi5S.psi5sChannel, data))
    {
        /* wait till data transfer is completed*/
        while (g_Psi5S.psi5s.psi5s->INTSTAT[IfxPsi5s_ChannelId_4].B.TPI == 0)
        {}
    }

    /* enable ASC receiver*/
    IfxPsi5s_Psi5s_enableAscReceiver(&g_Psi5S.psi5s);

    /* start ASC interface*/
    IfxPsi5s_Psi5s_startAscTransactions(&g_Psi5S.psi5s);

    IfxPsi5s_Psi5s_Frame frame;

    while (!IfxPsi5s_Psi5s_getReadFrameStatus(&g_Psi5S.psi5s, IfxPsi5s_ChannelId_4))
    {}

    IfxPsi5s_Psi5s_readFrame(&g_Psi5S.psi5sChannel, &frame);

    printf("Received frame:\nData=%x\nStatus=%x\nTime stamp=%x\n", frame.data, frame.status, frame.timestamp);
}
