/**
 * \file HsslStreamingDemo.c
 * \brief Demo HsslStreamingDemo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "HsslStreamingDemo.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/

App_HsslStreaming g_HsslStreaming; /**< \brief Demo information */

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

uint32 IFX_ALIGN(256) txData[80];

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \addtogroup IfxLld_Demo_HsslStreaming_SrcDoc_Main_Interrupt
 * \{ */

/** \} */

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void HsslStreamingDemo_init(void)
{
	/* create Hsct module config */
	IfxHssl_Hssl_initHsctModuleConfig(&g_HsslStreaming.drivers.hsctConfig, &MODULE_HSCT0);

	/* choose master or slave */
	g_HsslStreaming.drivers.hsctConfig.interfaceMode = IfxHssl_InterfaceMode_master;
	g_HsslStreaming.drivers.hsctConfig.highSpeedMode = FALSE; /* interface at low speed */

	/* create Hssl module config */
	IfxHssl_Hssl_initHsslModuleConfig(&g_HsslStreaming.drivers.hsslConfig, &MODULE_HSSL0);

	/* initialize Hsct module */
	IfxHssl_Hssl_initHsctModule(&g_HsslStreaming.drivers.hsct, &g_HsslStreaming.drivers.hsctConfig);

	/* Changing Clock input to slave device as SysClk instead of fosc */
	if (g_HsslStreaming.drivers.hsctConfig.interfaceMode == IfxHssl_InterfaceMode_slave)
	{
		IfxScuCcu_Config IfxScuCcu_sampleClockConfig;
		IfxScuCcu_initConfig(&IfxScuCcu_sampleClockConfig);
		/* Set the clock to SysClk generated from HSCT master interface */
		IfxScuCcu_sampleClockConfig.pllInitialStepConfig.pllsParameters.pllInputClockSelection = IfxScuCcu_PllInputClockSelection_fSysclk;
        IfxScuCcu_init(&IfxScuCcu_sampleClockConfig);
        /* Wait till PLL is locked*/
		while (g_HsslStreaming.drivers.hsct.hsct->STATPHY.B.PLOCK == 0)                                      /* wait until pll is locked */
		{}
	}
	/* initialize Hssl module */
	IfxHssl_Hssl_initHsslModule(&g_HsslStreaming.drivers.hssl, &g_HsslStreaming.drivers.hsslConfig);

	/* create HSSL channel config */
	IfxHssl_Hssl_ChannelConfig hsslChannelConfig;
	IfxHssl_Hssl_initChannelConfig(&hsslChannelConfig, &g_HsslStreaming.drivers.hssl, &g_HsslStreaming.drivers.hsct);

	uint32 i;

	for (i = 0; i < 4; ++i)
	{
		hsslChannelConfig.channelId = (IfxHssl_ChannelId)i;

		if (i == 2)
		{
			/*			hsslChannelConfig.loopBack = TRUE;	// used in prepareStream Api */
		}

		IfxHssl_Hssl_initChannel(&g_HsslStreaming.drivers.hsslChannel[i], &hsslChannelConfig);
	}

	printf("Hssl is Initialized\n");
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void HsslStreamingDemo_run(void)
{
	if (g_HsslStreaming.drivers.hsctConfig.interfaceMode == IfxHssl_InterfaceMode_slave)
	{
		while (1)
		{}
	}
	else if (g_HsslStreaming.drivers.hsctConfig.interfaceMode == IfxHssl_InterfaceMode_master)
	{
		uint32 i    = 0;
		uint32 data = 0x12345600;

		for (i = 0; i < 80; i++)
		{
			txData[i] = data + i;
		}

		/* Enable reception at the Slave */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_enableReception);

		/* Inititate ping request to slave */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_ping);

		/* Changing speed of the target device from Low to High */

		g_HsslStreaming.drivers.hsct.hsct->IFCTRL.B.MRXSPEED = IfxHssl_MasterModeRxSpeed_highSpeed;

		/* Send interface commmand to change Rx to High speed at the target */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_highSpeedReception);

		/* Send interface commmand to change Tx to High speed at the target */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_highSpeedTransmission);

		g_HsslStreaming.drivers.hsct.hsct->IFCTRL.B.MTXSPEED = IfxHssl_MasterModeTxSpeed_highSpeed;

		/* Initiate ping request */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_ping);

		/* prepare streaming of single memory block */
		while ( IfxHssl_Hssl_prepareStream(&g_HsslStreaming.drivers.hsslChannel[0], 0x70008000, 10) != IfxHssl_Hssl_Status_ok) {

			/* Clear timeout interrupt if occured and retry */
			IfxHssl_clearHsslChannelErrorInterruptFlag(g_HsslStreaming.drivers.hssl.hssl,IfxHssl_Hssl_ERRInterruptSource_timeoutError,g_HsslStreaming.drivers.hsslChannel[0].channelId);
		}

		/* stream single memory block */
		IfxHssl_Hssl_writeStream(&g_HsslStreaming.drivers.hssl, (uint32 *)IFXCPU_GLB_ADDR_DSPR(IfxCpu_getCoreId(), (uint32)txData), 10);

		while (IfxHssl_Hssl_waitAcknowledge(&g_HsslStreaming.drivers.hsslChannel[2]) != IfxHssl_Hssl_Status_ok)
		{}

		/* Changing speed of the target device from High to Low */
		/* Send interface command to change Rx to low speed at the target */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_lowSpeedReception);

		g_HsslStreaming.drivers.hsct.hsct->IFCTRL.B.MRXSPEED = IfxHssl_MasterModeRxSpeed_lowSpeed;

		/* Send interface command to change Tx to low speed at the target */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_lowSpeedTransmission);

		g_HsslStreaming.drivers.hsct.hsct->IFCTRL.B.MTXSPEED = IfxHssl_MasterModeTxSpeed_lowSpeed;

		/* Initiate ping request */
		IfxHssl_Hssl_sendControlCommand(&g_HsslStreaming.drivers.hsct,IfxHssl_ControlCommand_ping);

		/* prepare streaming of single memory block */
		while ( IfxHssl_Hssl_prepareStream(&g_HsslStreaming.drivers.hsslChannel[0], 0x70008140, 10)!= IfxHssl_Hssl_Status_ok){

			IfxHssl_clearHsslChannelErrorInterruptFlag(g_HsslStreaming.drivers.hssl.hssl,IfxHssl_Hssl_ERRInterruptSource_timeoutError,g_HsslStreaming.drivers.hsslChannel[0].channelId);
		}
		/* stream single memory block */
		IfxHssl_Hssl_writeStream(&g_HsslStreaming.drivers.hssl, (uint32 *)IFXCPU_GLB_ADDR_DSPR(IfxCpu_getCoreId(), (uint32)txData), 10);

		while (IfxHssl_Hssl_waitAcknowledge(&g_HsslStreaming.drivers.hsslChannel[2]) != IfxHssl_Hssl_Status_ok)
		{}

		/* prepare streaming of single memory block */
		while ( IfxHssl_Hssl_prepareStream(&g_HsslStreaming.drivers.hsslChannel[0], 0x70008280, 10)!= IfxHssl_Hssl_Status_ok){

			IfxHssl_clearHsslChannelErrorInterruptFlag(g_HsslStreaming.drivers.hssl.hssl,IfxHssl_Hssl_ERRInterruptSource_timeoutError,g_HsslStreaming.drivers.hsslChannel[0].channelId);
		}
		/* stream single memory block */
		IfxHssl_Hssl_writeStream(&g_HsslStreaming.drivers.hssl, (uint32 *)IFXCPU_GLB_ADDR_DSPR(IfxCpu_getCoreId(), (uint32)txData), 10);

		while (IfxHssl_Hssl_waitAcknowledge(&g_HsslStreaming.drivers.hsslChannel[2]) != IfxHssl_Hssl_Status_ok)
		{}

	}

	printf("Hssl data Streaming is finished\n");
}
