/**
 * \file DmaBasicDemo.c
 * \brief Dma basic Memory to memory transfer Demo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "Cpu0_Main.h"
#include "ConfigurationIsr.h"
#include "Ifx_Assert.h"
#include "DmaBasicDemo.h"

/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
App_DmaBasic g_DmaBasic; /**< \brief Dma global data */

/* The aligment is set 64 bit since circular buffer is configured to 64 bit.   /
 * The User needs to configure the same depeding on their use-case			  */

volatile uint32 IFX_ALIGN(64) source[NUM_CHANNELS][BUFFER_SIZE]; /**< \brief source buffer */ 
volatile uint32 IFX_ALIGN(64) destination[NUM_CHANNELS][BUFFER_SIZE]; /**< \brief destination buffer */

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/
/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void IfxDmaBasicDemo_init(void)
{
    uint32                   i, j;

    /* create module config */
    IfxDma_Dma_Config        dmaConfig;
    IfxDma_Dma_initModuleConfig(&dmaConfig, &MODULE_DMA);

    /* initialize module */
    IfxDma_Dma               dma;
    IfxDma_Dma_initModule(&dma, &dmaConfig);

    /* initial configuration for all channels */
    IfxDma_Dma_ChannelConfig cfg;
    IfxDma_Dma_initChannelConfig(&cfg, &dma);

    /* following configuration is used by all channels */
    cfg.transferCount                    = BUFFER_SIZE;
    cfg.requestMode                      = IfxDma_ChannelRequestMode_completeTransactionPerRequest;
    cfg.moveSize                         = IfxDma_ChannelMoveSize_32bit;

    cfg.destinationAddressCircularRange  = IfxDma_ChannelIncrementCircular_64;
    cfg.sourceAddressCircularRange       = IfxDma_ChannelIncrementCircular_64;
    cfg.destinationCircularBufferEnabled = TRUE;
    cfg.sourceCircularBufferEnabled      = TRUE;

    /* channel specific configurations */
    for (i = 0; i < NUM_CHANNELS; ++i)
    {
        cfg.channelId          = (IfxDma_ChannelId)i;
        cfg.sourceAddress      = IFXCPU_GLB_ADDR_DSPR(IfxCpu_getCoreId(), &source[i][0]);
        cfg.destinationAddress = IFXCPU_GLB_ADDR_DSPR(IfxCpu_getCoreId(), &destination[i][0]);
        IfxDma_Dma_initChannel(&g_DmaBasic.drivers.chn[i], &cfg);
    }

    /* prepare buffers */
    for (i = 0; i < NUM_CHANNELS; ++i)
    {
        uint32 *src     = (uint32 *)&source[i];
        uint32 *dst     = (uint32 *)&destination[i];
        uint32  chnWord = i * 0x10000000;

        for (j = 0; j < BUFFER_SIZE; ++j)
        {
            *src++ = chnWord++;
            *dst++ = 0xdeadbeef;
        }
    }
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void IfxDmaBasicDemo_run(void)
{
    uint32  errors = 0;
    uint32  i, j;
    boolean notFinished;

    printf("Starting DMA transfer on all %d channels\n", NUM_CHANNELS);

    for (i = 0; i < NUM_CHANNELS; ++i)
    {
        IfxDma_Dma_startChannelTransaction(&g_DmaBasic.drivers.chn[i]);
    }

    do
    {
        notFinished = FALSE;

        for (i = 0; i < NUM_CHANNELS; ++i)
        {
            if (IfxDma_getChannelTransferCount(g_DmaBasic.drivers.chn[i].dma, g_DmaBasic.drivers.chn[i].channelId))
            {
                notFinished = TRUE;
                break;
            }
        }
    } while (notFinished);

    printf("All transactions finished\n");

    printf("Checking destinationBuffer\n");

    for (i = 0; i < NUM_CHANNELS; ++i)
    {
        uint32 *dst     = (uint32 *)&destination[i];
        uint32  chnWord = i * 0x10000000;

        for (j = 0; j < BUFFER_SIZE; ++j)
        {
            if (*dst++ != chnWord++)
            {
                ++errors;
            }
        }
    }

    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, errors == 0);

    if (errors)
    {
        printf("ERROR: Dma destination data doesn't match with expected data (%lu mismatches)\n", errors);
    }
    else
    {
        printf("OK: Dma destination data matches with expected data\n");
    }
}
