/**
 * \file EmemBasicDemo.c
 * \brief Demo EmemBasicDemo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "EmemBasicDemo.h"
#include "_Utilities/Ifx_Assert.h"
#include <Emem/Std/IfxEmem.h>
#include <Stm/Std/IfxStm.h>
#include <Cpu/Std/IfxCpu.h>
#include <Mtu/Std/IfxMtu.h>
/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
App_EmemBasic g_EmemBasic; /**< \brief Demo information */

/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void EmemBasicDemo_init(void)
{
    if (IfxEmem_isModuleEnabled() != TRUE)
    {
        IfxEmem_enableModule(&MODULE_EMEM);
    }

    IfxStm_waitTicks(&MODULE_STM0, 10);

    if (IfxEmem_LockedState_locked == IfxEmem_getLockedState())
    {
        /* apply unlock sequence */
        IfxEmem_setUnlockStandbyLockFlag(0x1);
        IfxEmem_setUnlockStandbyLockFlag(0x3);
        IfxEmem_setUnlockStandbyLockFlag(0x7);
        /* wait one cycle for unlock */

        IfxStm_waitTicks(&MODULE_STM0, 10);
    }

    IfxEmem_setTileConfigMode(IfxEmem_TileConfigMode_calibMode, IfxEmem_TileNumber_0);

    /* Enable the MTU and perform ClearSram before memory is accessed
     * In the demo since only tile0 is used, we are clearing only the SSH required
     * for the same. The user to adapt this accordingly.
     */
    {
        /* Enable the MTU clock */
        IfxMtu_enableModule();

        /* Clear SRAM */
        IfxMtu_clearSram(IfxMtu_MbistSel_ememUpper0);
    }

    {
        uint64 *pmem;
        uint32  i;

        /* initialize the whole EMEM with 0 */
        pmem = (uint64 *)IFXEMEM_START_ADDR_CPU;

        for (i = 0; (uint64)i < (IFXEMEM_SIZE / IFXEMEM_TILE_SIZE); i += 1)
        {
            *(pmem++) = (uint64)0xAAAAAAAA55555555;
        }
    }
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void EmemBasicDemo_run(void)
{
    volatile uint64 *Emem;
    uint32           error = 0;
    uint32           i;
    uint64           value = 0x1;
    printf("EmemBasicDemo_run() called\n");
    Emem = (uint64 *)IFXEMEM_START_ADDR_CPU;

    for (i = 0; (uint64)i < (IFXEMEM_SIZE / IFXEMEM_TILE_SIZE); i += 1)
    {
        *(Emem++) = (uint64)value++;
    }

    Emem  = (uint64 *)IFXEMEM_START_ADDR_CPU;
    value = 0x1;

    for (i = 0; (uint64)i < (IFXEMEM_SIZE / IFXEMEM_TILE_SIZE); i += 1)
    {
        if (*(Emem++) != value)
        {
            error++;
        }

        IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, error == 0);

        if (error)
        {
            printf("ERROR: found %d errors\n", error);
        }
        else
        {
            printf("OK: checks passed \n");
        }

        value++;
    }
}
