/**
 * \file FceBasicDemo.c
 * \brief Demo FceBasicDemo
 *
 * \version iLLD_Demos_1_0_1_15_0
 * \copyright Copyright (c) 2014 Infineon Technologies AG. All rights reserved.
 *
 *
 *                                 IMPORTANT NOTICE
 *
 * Use of this file is subject to the terms of use agreed between (i) you or
 * the company in which ordinary course of business you are acting and (ii)
 * Infineon Technologies AG or its licensees. If and as long as no such terms
 * of use are agreed, use of this file is subject to following:
 *
 * Boost Software License - Version 1.0 - August 17th, 2003
 *
 * Permission is hereby granted, free of charge, to any person or organization
 * obtaining a copy of the software and accompanying documentation covered by
 * this license (the "Software") to use, reproduce, display, distribute,
 * execute, and transmit the Software, and to prepare derivative works of the
 * Software, and to permit third-parties to whom the Software is furnished to
 * do so, all subject to the following:
 *
 * The copyright notices in the Software and this entire statement, including
 * the above license grant, this restriction and the following disclaimer, must
 * be included in all copies of the Software, in whole or in part, and all
 * derivative works of the Software, unless such copies or derivative works are
 * solely in the form of machine-executable object code generated by a source
 * language processor.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
 * SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
 * FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
 * DEALINGS IN THE SOFTWARE.
 */

/******************************************************************************/
/*----------------------------------Includes----------------------------------*/
/******************************************************************************/

#include <stdio.h>
#include "FceBasicDemo.h"
#include "_Utilities/Ifx_Assert.h"
#include <Cpu/Std/IfxCpu.h>
/******************************************************************************/
/*-----------------------------------Macros-----------------------------------*/
/******************************************************************************/
#define CHECK_DATA_SIZE 25
/******************************************************************************/
/*--------------------------------Enumerations--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-----------------------------Data Structures--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------------Global variables------------------------------*/
/******************************************************************************/
App_FceBasic g_FceBasic; /**< \brief Demo information */
/* data over which CRC should be calculated
 * generated with following perl script:
 * srand(42);
 */
uint32 checkData[CHECK_DATA_SIZE] = {
    0xbe9957bb,
    0x1c706c1e,
    0x14c3db3f,
    0x7fb17a93,
    0xb0d9d5a7,
    0x768093e0,
    0x88b206a0,
    0xc51299e4,
    0xe8a97d48,
    0x89367f27,
    0x70095984,
    0xec030f75,
    0xdc22f8d4,
    0xd951407b,
    0x34ae18c6,
    0x4d47ba7d,
    0x0e2e4622,
    0x4a2e90d3,
    0xdaec3752,
    0xcd3ed11c,
    0x36b416b7,
    0x8ea28658,
    0xdd37eee3,
    0x23928b62,
    0x84eb4b22,
};
/******************************************************************************/
/*-------------------------Function Prototypes--------------------------------*/
/******************************************************************************/

/******************************************************************************/
/*------------------------Private Variables/Constants-------------------------*/
/******************************************************************************/

/******************************************************************************/
/*-------------------------Function Implementations---------------------------*/
/******************************************************************************/
/** \addtogroup IfxLld_Demo_FceBasicDemo_SrcDoc_Main_Interrupt
 * \{ */

/** \name Interrupts for <fceISR> check length & CRC mismatch error, Bus & Configuration Error
 * \{ */
IFX_INTERRUPT(fceISR, 0, ISR_PRIORITY_FCE0)
{
    {
        Ifx_FCE_IN_STS interruptStatus = IfxFce_Crc_getInterruptStatus(&g_FceBasic.fceCrc32_0);

        if (interruptStatus.U)
        {
            if (interruptStatus.B.CMF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.CEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.LEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.BEF == 1)
            {
                g_FceBasic.error++;
            }
        }

        IfxFce_Crc_clearErrorFlags(&g_FceBasic.fceCrc32_0);
    }

    {
        Ifx_FCE_IN_STS interruptStatus = IfxFce_Crc_getInterruptStatus(&g_FceBasic.fceCrc32_1);

        if (interruptStatus.U)
        {
            if (interruptStatus.B.CMF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.CEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.LEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.BEF == 1)
            {
                g_FceBasic.error++;
            }
        }

        IfxFce_Crc_clearErrorFlags(&g_FceBasic.fceCrc32_1);
    }

    {
        Ifx_FCE_IN_STS interruptStatus = IfxFce_Crc_getInterruptStatus(&g_FceBasic.fceCrc16);

        if (interruptStatus.U)
        {
            if (interruptStatus.B.CMF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.CEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.LEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.BEF == 1)
            {
                g_FceBasic.error++;
            }
        }

        IfxFce_Crc_clearErrorFlags(&g_FceBasic.fceCrc16);
    }

    {
        Ifx_FCE_IN_STS interruptStatus = IfxFce_Crc_getInterruptStatus(&g_FceBasic.fceCrc8);

        if (interruptStatus.U)
        {
            if (interruptStatus.B.CMF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.CEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.LEF == 1)
            {
                g_FceBasic.error++;
            }

            if (interruptStatus.B.BEF == 1)
            {
                g_FceBasic.error++;
            }
        }

        IfxFce_Crc_clearErrorFlags(&g_FceBasic.fceCrc8);
    }
}
/** \} */

/** \} */

/** \brief Demo init API
 *
 * This function is called from main during initialization phase
 */
void FceBasicDemo_init(void)
{
    /* disable interrupts */
    boolean           interruptState = IfxCpu_disableInterrupts();

    /* create module config */
    IfxFce_Crc_Config fceConfig;
    IfxFce_Crc_initModuleConfig(&fceConfig, &MODULE_FCE);

    /* ISR priorities and interrupt target */
    fceConfig.isrPriority      = ISR_PRIORITY_FCE0;
    fceConfig.isrTypeOfService = ISR_PROVIDER_FCE0;

    /* initialize module */
    IfxFce_Crc_initModule(&g_FceBasic.fce, &fceConfig);

    /*initialize CRC kernels */
    IfxFce_Crc_CrcConfig crcConfig;
    IfxFce_Crc_initCrcConfig(&crcConfig, &g_FceBasic.fce);
    crcConfig.enabledInterrupts.crcMismatch = TRUE;
    crcConfig.enabledInterrupts.configError = TRUE;
    crcConfig.enabledInterrupts.lengthError = TRUE;
    crcConfig.enabledInterrupts.busError    = TRUE;
   
   //CRC kernel 0: IEEE 802.3 CRC32 ethernet polynomial
    crcConfig.crcKernel= IfxFce_CrcKernel_0;
    IfxFce_Crc_initCrc(&g_FceBasic.fceCrc32_0, &crcConfig);

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);
}


/** \brief Demo run API
 *
 * This function is called from main, background loop
 */
void FceBasicDemo_run(void)
{
    uint32 expected;
    expected = 0xd95def75;
    printf("FceBasicDemo_run() called\n");

    {
        /* Expected CRC: */
        g_FceBasic.fceCrc32_0.expectedCrc = 0xd95def75;
        /* do calculation */
        uint32 fceCrc = IfxFce_Crc_calculateCrc(&g_FceBasic.fceCrc32_0, checkData, CHECK_DATA_SIZE, 0x00000000);

        if (expected != fceCrc)
        {
            g_FceBasic.error++;
        }
    }

    IFX_ASSERT(IFX_VERBOSE_LEVEL_ERROR, g_FceBasic.error == 0);

    if (g_FceBasic.error)
    {
        printf("ERROR: found %d errors\n", g_FceBasic.error);
    }
    else
    {
        printf("OK: checks passed \n");
    }
}
